# Generated by Django 5.2.5 on 2025-08-19 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='tag_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contents.tags'),
        ),
    ]
