# Generated by Django 5.2.5 on 2025-09-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0002_alter_contents_tag_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stamps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Targets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("value", models.IntegerField()),
            ],
        ),
    ]
