# Generated by Django 5.2.5 on 2025-09-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0003_stamps_targets"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name="stamps",
            options={"get_latest_by": "created_at"},
        ),
        migrations.AlterField(
            model_name="contents",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
