# Generated by Django 5.2.5 on 2025-09-30 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0004_tag_alter_stamps_options_alter_contents_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contents",
            name="tag_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contents.tags",
                to_field="tag_name",
            ),
        ),
    ]
