# Generated by Django 5.2.5 on 2025-09-30 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0005_alter_contents_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contents",
            name="tag_name",
            field=models.ForeignKey(
                db_column="tag_name",
                on_delete=django.db.models.deletion.PROTECT,
                to="contents.tags",
                to_field="tag_name",
            ),
        ),
    ]
