# Generated by Django 5.2.5 on 2025-09-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0006_alter_contents_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contents",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
